theme: jekyll-theme-minimal
title: Charles Ashton
description: Data/Research Professional
logo: https://avatars.githubusercontent.com/u/93352455?s=400&u=7d5b966513537419a5f73715e760bca9a6867bf9&v=4
show_downloads: false
